### DISCUSSION TITLE
Auto Discover Region Failure

### DISCUSSION THREAD

**Discussion by comradepanda** [CrowdStrike/ansible_collection_falcon#240] [Q&A] [answered]
Hey team, 

I am getting this error: 
```
fatal: [<HOST>]: FAILED! => {"msg": "The conditional check 'falcon_api_oauth2_token.x_cs_region|length > 0' failed. 
The error was: error while evaluating conditional (falcon_api_oauth2_token.x_cs_region|length > 0): 'dict object' has no attribute 'x_cs_region'

The error appears to be in '/home/<USER>/.ansible/collections/ansible_collections/crowdstrike/falcon/roles/falcon_install/tasks/api.yml': line 17, column 3, but may

be elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:

- name: CrowdStrike Falcon | Auto-discover CrowdStrike Cloud Region\n  ^ here"}
```

Here is my playbook
```
- hosts: all
  vars:
    falcon_cloud: https://api.us-2.crowdstrike.com
    falcon_client_id: <API KEY ID>
    falcon_client_secret: <KEY MATERIAL>
  roles:
  - role: crowdstrike.falcon.falcon_install
    vars:
      falcon_sensor_version_decrement: 2
  - role: crowdstrike.falcon.falcon_configure
    vars:
      falcon_tags: 'taggy tags'
```
