### DISCUSSION TITLE
Playbook examples

### DISCUSSION THREAD

**Discussion by txsastre** [CrowdStrike/ansible_collection_falcon#374] [Q&A] [answered]
hi there
I've been all the day testing with the ansible collection facon.
but I've been unable to acomplish, I tried method API, URL and file, but none has worked.

Can someone put some example playbooks to see where can I be wrong and learn ?

thanks.

**Comment by carlosmmatos** [comment, marked as answer]
Hey @txsastre I'm sorry I'm just seeing this. Here is what I would recommend in terms of order or "getting started":
1. Make sure you are installing this collection and dependencies accordingly: [read here](https://www.falconpy.io/Service-Collections/Prevention-Policy.html)
2. Each role has a README with example playbooks at the bottom: [falcon_install](https://github.com/CrowdStrike/ansible_collection_falcon/blob/main/roles/falcon_install/README.md)
3. Once you are familiar with 1 & 2: The simplest way to get started is to use a playbook as such:

```yaml
---
- hosts: all
  roles:
  - role: crowdstrike.falcon.falcon_install
    vars:
      falcon_client_id: <FALCON_CLIENT_ID>
      falcon_client_secret: <FALCON_CLIENT_SECRET>
```

### Things to note
- The interactions with the Falcon API's are done by localhost.
- You don't need to worry about adding `become:` clauses as the roles already handle this for you
- If you are still having issues, run in verbosity mode `-vvv` and open up an issue here so we can further help you.
