### ISSUE TITLE
win uninstall doesnt find the executable

### ISSUE THREAD

**Issue by smoothzz** [CrowdStrike/ansible_collection_falcon#180]
when trying to uninstall in a windows machine, the role couldnt find the executable to pass the arguments, the file now is named as "WindowsSensor.MaverickGyr.x64.exe" not "WindowsSensor.exe" anymore.

What i did to fix it was searching for a pattern regex in that case works just fine.

Thanks

```
- name: CrowdStrike Falcon | Find Windows installer in Package Cache
    ansible.windows.win_find:
      paths: C:\ProgramData\Package Cache
      patterns: ^(WindowsSensor.*\.)(exe)$
      recurse: yes
      use_regex: yes
    register: falcon_win_sensor_cache
```
