### ISSUE TITLE
Kernel Supported by Latest Sensor but install failed  at Validate Sensor version is compatible with Kernel

### ISSUE THREAD

**Issue by nhempenius** [CrowdStrike/ansible_collection_falcon#208]
On July 6th one of our Sensor install jobs failed at the `Validate Sensor version is compatible with Kernel` task with message `The sensor version: 6.41.13803 is not supported with kernel: 3.10.0-1160.2.2.el7.x86_64.`  
According to the sensor-update-kernels API this kernel was supported at version 6.33.13005.

To fix the issue we modified `falcon_sensor_version_decrement: 0` to `falcon_sensor_version_decrement: 2`.  The job finished successfully by using sensor version: 6.39.0-13601.
This particular hosts sensors has since automatically updated its version to latest (6.41.13804.0) without issue, per its sensor update policy.

I noticed in the release notes that sensor version 6.41.13803 was released on July 5th,2022 and this installation attempted was on ~ Jul. 6, 2022 11:17:04. My theory is there is a lag between when a sensor version is available to download and when its populated into the into the base_package_supported_sensor_versions  field returned by the sensor-update-kernels API for that specific kernel.

Our current resolution is to re-run jobs with an increased version_decrement. However we would like to avoid that. Would it be possible to automatically increase the version_decrement and re-run the `Validate Sensor version is compatible with Kernel` task?

The Ansible file used for the FAILED Job:
```
---
- name: Crowdstrike Install
  hosts: all
  vars:
   falcon_client_id: <Client ID>
   falcon_client_secret: <Client Password>
  roles:
  - role: crowdstrike.falcon.falcon_install
    vars:
     falcon_sensor_version_decrement: 0
  - role: crowdstrike.falcon.falcon_configure
    vars:
    falcon_tags: '<TAG>’
```

Error for FAILED job:

```
TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Validate Sensor version is compatible with Kernel] ***
task path: /tmp/awx_10504_rejfi0io/requirements_collections/ansible_collections/crowdstrike/falcon/roles/falcon_install/tasks/api.yml:114
fatal: [192.168.101.85]: FAILED! => {
    "assertion": "falcon_sensor_version in falcon_base_package_supported_sensor_versions or falcon_sensor_version in falcon_ztl_supported_sensor_versions or falcon_sensor_version in falcon_ztl_module_supported_sensor_versions",
    "changed": false,
    "evaluated_to": false,
    "msg": "The sensor version: 6.41.13803 is not supported with kernel: 3.10.0-1160.2.2.el7.x86_64"
}
```

The Ansible file used for the SUCCESSFUL Job:
```
---
- name: Crowdstrike Install
  hosts: all
  vars:
   falcon_client_id: <Client ID>
   falcon_client_secret: <Client Password>
  roles:
  - role: crowdstrike.falcon.falcon_install
    vars:
     falcon_sensor_version_decrement: 2
  - role: crowdstrike.falcon.falcon_configure
    vars:
    falcon_tags: '<TAG>’
```

Sensor version that was installed for SUCCESSFUL Job (Same Kernel):
```
changed: [192.168.101.85] => {
    "changed": true,
    "changes": {
        "installed": [
            "/tmp/ansible.FUouwafalcon/falcon-sensor-6.39.0-13601.el7.x86_64.rpm"
        ]
    }
```
