### ISSUE TITLE
follow_redirects missing in falcon_configure role

### ISSUE THREAD

**Issue by carlosmmatos** [CrowdStrike/ansible_collection_falcon#217]
From a discussion post -

Hello @carlosmmatos ,

I'm using this collection and I'm encountering issues because the `follow_redirects` option is not set.
I'm not setting any specific URL to my playbook, but when I do a simple configure without calling the install role first, I always end up with an error on the API authentication.
I'm redirected from `api.crowdstrike.com` to `api.us-2.crowdstrike.com`. Does that mean that I should specifically set it to `api.us-2.crowdstrike.com`?
The `falcon_cloud` variable is indeed used in the configure role, but it's not part of the list in the README.

FYI in the code of the install role, the redirects are still followed:
https://github.com/CrowdStrike/ansible_collection_falcon/blob/6e5f130331d8ead7611967706e886bd787ea5cf6/roles/falcon_install/tasks/api.yml#L10

Error:
```
fatal: [REDACTED]: FAILED! => changed=false
  connection: close
  content: ''
  content_length: '0'
  date: Mon, 25 Jul 2022 13:07:06 GMT
  elapsed: 0
  location: https://api.us-2.crowdstrike.com/oauth2/token
  msg: 'Status code was 308 and not [201]: HTTP Error 308: Permanent Redirect'
  redirected: false
  server: nginx
  status: 308
  strict_transport_security: max-age=31536000; includeSubDomains
  url: https://api.crowdstrike.com/oauth2/token
  x_cs_region: us-2
  x_cs_traceid: REDACTED
  x_ratelimit_limit: '300'
  x_ratelimit_remaining: '299'
```

Playbook used:
```yaml
- name: "include_role | crowdstrike.falcon.falcon_configure"
  include_role:
    name: crowdstrike.falcon.falcon_configure
  vars:
    falcon_tags: "{{ crowdstrike_falcon_tags }}"
  tags:
    - falcon-agent-configure
```

_Originally posted by @rnsc in https://github.com/CrowdStrike/ansible_collection_falcon/discussions/192#discussioncomment-3222473_
