### ISSUE TITLE
Install directory/documentation

### ISSUE THREAD

**Issue by NateLedet** [CrowdStrike/ansible_collection_falcon#23]
In the defaults/main.yml file, the documentation shows:
```
# Where should the sensor file be downloaded to? By default
# this will be the homedir of the user the ansible playbook
# is running as.
```

Within tasks/preinstall.yml, we have this code, which is setting it to the /tmp/ directory:

```
- set_fact:
    falcon_install_tmp_dir: "/tmp/"
  when:
    - not falcon_install_tmp_dir
    - ansible_system == "Linux" or ansible_system == "Darwin"
```

Should that be updated to the user's directory?

```
- set_fact:
    falcon_install_tmp_dir: "{{ ansible_user_dir }}"
```

Thanks
