### ISSUE TITLE
Error: Get list of supported Kernels

### ISSUE THREAD

**Issue by patrickmayes** [CrowdStrike/ansible_collection_falcon#246]
We are getting the following error message with using Ansible version 2.11 via AWX and this collection on versions 3.2.18, 3.2.19, and 3.2.20

### Error Message from AWX
```
TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Get list of Supported Kernels] ***13:32:38
1010
Tuesday 23 August 2022 18:32:38 +0000 (0:00:00.100) 0:00:46.267 ********
1011
fatal: [ldd7f54_42038e6e-abb4-3f5f-d0da-6e310a889751]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
```

### Var falcon_sensor_update_kernels_query output
```
"falcon_sensor_update_kernels_query": "vendor:\"ubuntu\"+release:\"5.15.0-41-generic\""
```

### Request to make troubleshooting easier
It would be nice if we had something like the following for EVERY variable that your role uses so if we put items into a debug mode like `-vvv` it would display and we could catch the error easier rather than being no_log and not being able to see what failed.

```
- name: Show variable (falcon_client_id) in Debug Mode
  ansible.builtin.debug:
    var: falcon_client_id
    verbosity: 3
```

### Ansible variable configuration
Also would like to confirm that the following is all that is needed in order to use the `install` role in your collection for both Linux and Windows and that Install is working for the following OS's Ubuntu (18, 20, 22), RHEL (7, 8), CentOS7, and Windows Server (2016, 2019, 2022)

#### vars
```
---
falcon_sensor_version_decrement: 1

falcon_client_id: "{{ lookup('vars', 'vault_client_id') }}"

falcon_client_secret: "{{ lookup('vars', 'vault_client_secret') }}"

falcon_cloud: "api.crowdstrike.com"

falcon_install_method: "api"

falcon_windows_tmp_dir: c:\thd\packages\
```

#### tasks/set_facts.yml
```
---
- name: Set QA Facts
  ansible.builtin.set_fact:
    falcon_cid: REDACTED
  when: REDACTED

- name: Set PR Facts
  ansible.builtin.set_fact:
    falcon_cid: REDACTED
  when: REDACTED
```
