### ISSUE TITLE
falcon_provisioning_token is always defined

### ISSUE THREAD

**Issue by Trane9991** [CrowdStrike/ansible_collection_falcon#32]
Hello, 
PR #15  introduced the `falcon_provisioning_token` parameter in the `defaults`,

which makes the condition `falcon_provisioning_token is not defined` to be **always false**, because variables in the `defaults` seem to be always defined.

This introduces the problem that step `CrowdStrike Falcon | Associate Falcon Sensor with your Customer ID (CID)` is never executed while `CrowdStrike Falcon | Associated Falcon Sensor with your Customer ID (CID) Using Provisioning Token` is running all the time.

To debug I added the following steps before the `CrowdStrike Falcon | Associate Falcon Sensor with your Customer ID (CID)` step:
```yml
  - debug:
          var: falcon_provisioning_token

  - debug:
          msg: "{{falcon_provisioning_token is not defined}}"
```

This is the result:
```
TASK [falcon_installation : CrowdStrike Falcon | Verify Falcon Package Is Installed] ****************************************************************************************************************
ok: [127.0.0.1]

TASK [falcon_installation : debug] ******************************************************************************************************************************************************************
ok: [127.0.0.1] => {
    "falcon_provisioning_token": null
}

TASK [falcon_installation : debug] ******************************************************************************************************************************************************************
ok: [127.0.0.1] => {
    "msg": false
}

TASK [falcon_installation : CrowdStrike Falcon | Associate Falcon Sensor with your Customer ID (CID)] ***********************************************************************************************
skipping: [127.0.0.1]

TASK [falcon_installation : CrowdStrike Falcon | Associated Falcon Sensor with your Customer ID (CID) Using Provisioning Token] *********************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": ["/opt/CrowdStrike/falconctl", "-s", "-f", "--cid=blablablabla, "--provisioning-token="]
```

However, if I remove the `falcon_provisioning_token` from defaults - everything works as expected:
```
TASK [falcon_installation : debug] ******************************************************************************************************************************************************************
ok: [127.0.0.1] => {
    "falcon_provisioning_token": "VARIABLE IS NOT DEFINED!"
}

TASK [falcon_installation : debug] ******************************************************************************************************************************************************************
ok: [127.0.0.1] => {
    "msg": true
}

TASK [falcon_installation : CrowdStrike Falcon | Associate Falcon Sensor with your Customer ID (CID)] ***********************************************************************************************
changed: [127.0.0.1]
```

So two possible solutions here:
1. Remove the definition of `falcon_provisioning_token` from `defaults`
2. Change the condition to `not falcon_provisioning_token` instead of `falcon_provisioning_token is not defined`

**Comment by NateLedet** [comment]
I found it helpful to have the variables in defaults, but you're right that the empty variable is now "defined", even if it is empty and causes issues. I had some issues with bare variables throwing errors and evaluating to false (see #26 ) which adding `is defined` seemed to fix, but your PR made me realize we could do more. 

What about checking if the variable is defined but empty? Haven't tested this but it could work? 

```
  - name: CrowdStrike Falcon | Associate Falcon Sensor with your Customer ID (CID)
    command: "/opt/CrowdStrike/falconctl -s -f --cid={{ falcon_cid }}"
    when:
      - (falcon_provisioning_token is not defined) or (falcon_provisioning_token == "")
      - (falcon_cid is defined) and (falcon_cid|length > 0)
```

```
  - name: CrowdStrike Falcon | Associated Falcon Sensor with your Customer ID (CID) Using Provisioning Token
    command: "/opt/CrowdStrike/falconctl -s -f --cid={{ falcon_cid }} --provisioning-token={{ falcon_provisioning_token }}"
    when:
      - (falcon_provisioning_token is defined) and (falcon_provisioning_token|length > 0)
      - (falcon_cid is defined) and (falcon_cid|length > 0)
```
