### ISSUE TITLE
Allow to provide grouping tags

### ISSUE THREAD

**Issue by Trane9991** [CrowdStrike/ansible_collection_falcon#34]
Provide a way to set grouping tags: https://answers.uillinois.edu/illinois/page.php?id=100806

**Comment by Trane9991** [comment]
Current workaround I used:

```yaml
  vars:
    falcon_grouping_tags: Production,Application
  tasks:
    - import_role:
        name: crowdstrike.falcon.falcon_installation

    - name: Set Custom Falcon Agent Tags
      command: "/opt/CrowdStrike/falconctl -s -f --tags={{falcon_grouping_tags}}"
      when:
      - ansible_distribution != "MacOSX"

    - name: Restarting Falcon Sensor Daemon (Linux)
      service:
        name: falcon-sensor
        state: restarted
      when:
        - falcon_cid is defined
        - installed_sensor in ansible_facts.packages
```
