### ISSUE TITLE
Install Windows is hanging Even though app is installed and service is running

### ISSUE THREAD

**Issue by iasllanih** [CrowdStrike/ansible_collection_falcon#358]
Ansible Core Version: 2.12.10

When running the install windows task for CS version 6.52.16606, ansible hangs and there arent any installer/powershell processes running, suggesting the tool has finished configuring the software.

However, the host does not show up in the CS console. When we run the install manually, everything checks out fine

The ansible code includes a pre req that pulls the package down locally then runs the community install task:
```yaml
- name: Download Crowdstrike From Network Source
  ansible.windows.win_get_url:
    url: "{{ artifact_repository }}{{ crowdstrike_extension }}{{ crowdstrike_installer }}"
    dest: C:\temp

- name: CrowdStrike Falcon | Install Falcon Sensor .exe Package (Windows)
  ansible.windows.win_package:
    path: 'C:\temp\{{ crowdstrike_installer }}'
    state: present
    creates_service: csfalconservice
    arguments: '/install /quiet CID={{ falcon_cid }} {{ falcon_windows_install_args }} GROUPING_TAGS="Test"'
  when:
    - ansible_facts['os_family'] == "Windows"
  register: falcon_installed
  retries: "{{ falcon_windows_install_retries }}"
  delay: "{{ falcon_windows_install_delay }}"
  until: falcon_installed is success
```
Again, this doesnt happen with manual installs. Ansible never reports the config change (if we rerun we get "OK" only because the service exists) and the CS console does not see the host running CS.

![ansible collection issue](https://github.com/CrowdStrike/ansible_collection_falcon/assets/59832328/650ceb7f-c595-47a0-9d35-26200a6385c6)

**Comment by carlosmmatos** [comment]
@iasllanih Thanks for opening up an issue.. let me look into it.

**Comment by carlosmmatos** [comment]
@iasllanih So I'm not able to reproduce this yet. I can successfully install version `6.52.16606` and see that it installs, get's the proper grouping tag set, and shows up on the console. This is what I am using to test this out:

```yaml
  tasks:
    - name: Set Additional Windows Install Args (optional)
      set_fact:
        windows_install_args: "/norestart ProvToken={{ lookup('env', 'FALCON_PROV_TOKEN') }} GROUPING_TAGS=cmatos-test"
      when: lookup('env', 'FALCON_PROV_TOKEN')

    - name: Install Falcon Sensor
      ansible.builtin.include_role:
        name: crowdstrike.falcon.falcon_install
      vars:
        falcon_client_id: "{{ lookup('env', 'FALCON_CLIENT_ID') }}"
        falcon_client_secret: "{{ lookup('env', 'FALCON_CLIENT_SECRET') }}"
        falcon_sensor_update_policy_name: "test-falcon-update-from-policy"
        falcon_windows_install_args: "{{ windows_install_args if windows_install_args is defined else '/norestart' }}"
```

Here you can see that I'm setting `windows_install_args` to include ProvToken (make sure you are setting this if you are using maint tokens) and a sensor grouping tag that ensures the host lands in the appropriate host_group that uses the sensor update policy I want to enforce. In this case, I'm calling the `falcon_install` role and passing in the sensor update policy name (this has the version set to `6.52.16606`). I'm also overriding the `falcon_windows_install_args` default variable with my first task. 

Running this in verbose mode `-vvv`, I get the following output:
<details>
  <summary>Click to expand to see the output</summary>

  ```shell
  TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Build API Sensor Query based on Sensor Update Policy] ***
  ok: [default-win-falcon-install-policy] => {
      "ansible_facts": {
          "falcon_os_query": "os:\"Windows\"+os_version:\"\"+version:\"6.52.16606\""
      },
      "changed": false
  }
  ...
  ...
  TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Install Falcon Sensor .exe Package (Windows)] ***
  changed: [default-win-falcon-install-policy] => {
      "attempts": 1,
      "changed": true,
      "invocation": {
          "module_args": {
              "arguments": "/install /quiet CID=***** /norestart ProvToken=***** GROUPING_TAGS=cmatos-test",
              "chdir": null,
              "client_cert": null,
              "client_cert_password": null,
              "creates_path": null,
              "creates_service": "csfalconservice",
              "creates_version": null,
              "expected_return_code": [
                  0,
                  3010
              ],
              "follow_redirects": "safe",
              "force_basic_auth": false,
              "headers": null,
              "http_agent": "ansible-httpget",
              "log_path": null,
              "maximum_redirection": 50,
              "password": null,
              "path": "C:\\Windows\\Temp\\ansible.0w0nx3t2.jtyfalcon\\WindowsSensor.MaverickGyr.exe",
              "product_id": null,
              "provider": "auto",
              "proxy_password": null,
              "proxy_url": null,
              "proxy_use_default_credential": false,
              "proxy_username": null,
              "state": "present",
              "url_method": null,
              "url_password": null,
              "url_timeout": 30,
              "url_username": null,
              "use_default_credential": false,
              "use_proxy": true,
              "username": null,
              "validate_certs": true,
              "wait_for_children": false
          }
      },
      "rc": 0,
      "reboot_required": false
  }
  ```
</details>

My suggestions to you are the following for troubleshooting:
- When the sensor is being installed, check the logs at `C:\Windows\Temp\CrowdStrike Windows Sensor_2023xxxxx`
  - This file is usually a good indicator of what happens through the installation process and is useful to provide to CS support. Things to be on the lookout might be Return Codes or provisioning token not being provided (if applicable)
- Are you having this issue with any other sensor version?
- Hopefully your example is just to highlight what you are doing, and not directly modifying the Ansible collection itself. If you are modifying the collection itself, then I would suggest you do the following in order to not modify the collection and introduce issues that we can't test:

Example Playbook:
```yaml
---
- name: Install Falcon Sensor
  hosts: all
  vars:
    artifact_repository: "https://example.com/artifacts/"
    crowdstrike_extension: "exe"
    crowdstrike_installer: "CrowdStrike_6.52.16606.exe"
    sensor_dest: 'C:\temp'
  tasks:
    - name: Download Crowdstrike From Network Source
      ansible.windows.win_get_url:
        url: "{{ artifact_repository }}{{ crowdstrike_extension }}{{ crowdstrike_installer }}"
        dest: "{{ sensor_dest }}"

    - name: Install Falcon Sensor
      ansible.builtin.include_role:
        name: crowdstrike.falcon.falcon_install
      vars:
        falcon_client_id: "{{ lookup('env', 'FALCON_CLIENT_ID') }}"
        falcon_client_secret: "{{ lookup('env', 'FALCON_CLIENT_SECRET') }}"
        falcon_sensor_pkg: "{{ sensor_dest }}\\{{ crowdstrike_installer }}"
        falcon_windows_install_args: "'/norestart GROUPING_TAGS=Test' }}"
```

**Comment by iasllanih** [comment]
Hi @carlosmmatos 

AV install is part of a broader base role that we use to install software, so ideally, we want to avoid nested roles/collections.

which is why i instead just grabbed the task file and referenced the necessary variables.

However, using set fact to define the arguments, and passing that into the arguments parameter for win_package seemed to do the trick. We confirmed the visibility console side, as well as an update from the crowdstrike console properly removing the older binary. I think we are good to close this issue.

for reference, i adjusted the task file to this:

```
  - name: Download Crowdstrike 
    ansible.windows.win_get_url:
      url: "{{ artifact_repository }}{{ crowdstrike_extension }}{{ crowdstrike_installer }}"
      dest: C:\temp
  
  - name: Set Additional Windows Install Args (optional)
    set_fact:
      windows_install_args: "/install /quiet CID={{ crowdstrike_company_code }} /norestart GROUPING_TAGS=Test"
  
  - name: CrowdStrike Falcon | Install Falcon Sensor .exe Package (Windows)
    ansible.windows.win_package:
      path: 'C:\temp\{{ crowdstrike_installer }}'
      state: present
      creates_service: csfalconservice
      arguments: '{{ windows_install_args }}'
    when:
      - ansible_facts['os_family'] == "Windows"
    register: falcon_installed
    retries: "{{ falcon_windows_install_retries }}"
    delay: "{{ falcon_windows_install_delay }}"
    until: falcon_installed is success

```
