### ISSUE TITLE
Installation method URL (windows)

### ISSUE THREAD

**Issue by txsastre** [CrowdStrike/ansible_collection_falcon#372]
this is my playbook

```
---
- hosts: all
  roles:
  - role: crowdstrike.falcon.falcon_install
    vars:
      falcon_install_method: url
      falcon_download_url: 'http://192.168.70.202/software/WindowsSensor.LionLanner.exe'
      falcon_windows_tmp_dir: "%SYSTEMROOT%\\Temp"
      falcon_localfile_path: 'c:\temp'
      falcon_client_id: '45345345345345353453453453453535-A4'
      falcon_client_secret: 'A1234567'
      falcon_api_enable_no_log: false
```

when I running it, I receive this error:

> FAILED! => {
>     "msg": "The task includes an option with an undefined variable. The error was: '**ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'path'. 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'path**'\n\nThe error appears to be in '/home/tomeu/.ansible/collections/ansible_collections/crowdstrike/falcon/roles/falcon_install/tasks/win_url.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# Tasks for Installing CrowdStrike's Falcon Sensor via URL\n- name: CrowdStrike Falcon | Downloading Installation Package from URL (Windows)\n  ^ here\n"

Checked everything, but I don't know what i'm missing.

**Comment by carlosmmatos** [comment]
Let me look into it

**Comment by carlosmmatos** [comment]
@txsastre Just so you know, when not using `falcon_install_method: api` - you will need to provide the `falcon_cid` variable. So your example should be updated as such:
```yaml
---
- hosts: all
  roles:
  - role: crowdstrike.falcon.falcon_install
    vars:
      falcon_install_method: url
      falcon_download_url: 'http://192.168.70.202/software/WindowsSensor.LionLanner.exe'
      falcon_cid: KLJSDLKFJLKAKLSJDLF-XY
```

**Comment by txsastre** [comment]
Ok, thanks a lot about finding the bug and the orientation about the windows variable **falcon_cid**. 
I thought that **falcon_client_id** was the right one.

It's not working either, I guess is still the same bug.

**Comment by txsastre** [comment]
hi there, I downloaded as you explained.

now I see that the agent is getting installed, but in the ansible console seems that it never ends the procedure.

the actual playbook
```
---
- hosts: all
  roles:
  - role: crowdstrike.falcon.falcon_install
    vars:
      falcon_install_method: url
      falcon_download_url: 'http://192.168.70.134/software/WindowsSensor.LionLanner.exe'
      falcon_client_id: '123413234342342341423423423413432-E1'
      falcon_cid: '123413234342342341423423423413432-E1'
      falcon_client_secret: '12345678'
      falcon_api_enable_no_log: false

```

executed with -vvv

```


**TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Install Falcon Sensor .exe Package (Windows)] ********************************************** **
task path: /home/tomeu/.ansible/collections/ansible_collections/crowdstrike/falcon/roles/falcon_install/tasks/win_install.yml:2
Using module file /home/tomeu/.ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_package.ps1
Pipelining is enabled.
<192.168.70.162> ESTABLISH WINRM CONNECTION FOR USER: ansible on PORT 5985 TO 192.168.70.162
EXEC (via pipeline wrapper)
```
and stays that way forever...


but it seems correctly installed on windows 2019

check by console
![VirtualBoxVM_IYWGKBHLey](https://github.com/CrowdStrike/ansible_collection_falcon/assets/10468371/aecc565e-c0c3-4de8-82c9-92ceefae37a1)

Check by GUI
![VirtualBoxVM_FOzTkUUaOo](https://github.com/CrowdStrike/ansible_collection_falcon/assets/10468371/39132784-1aee-4b3a-afd9-ac086dd5ecf4)


if I stop the playbook and run again it says that the agent is already installed.
