### ISSUE TITLE
Instaltion method API (Windows)

### ISSUE THREAD

**Issue by txsastre** [CrowdStrike/ansible_collection_falcon#373]
Following the examples, I have this playbook

```
---
- hosts: all
  roles:
  - role: crowdstrike.falcon.falcon_install
    vars:
      falcon_client_id: "813EFADB098A4EAB0A3FF41B1B137EFB-E8"
      falcon_client_secret: "00B14D65"
      
      falcon_windows_tmp_dir: 'c:\temp'
      falcon_api_enable_no_log: false
```

but the result is always an "access denied, authorization failed"

`_fatal: [192.168.70.162]: FAILED! => {"changed": false, "character_set": "", "connection": "keep-alive", "content": "{\n \"meta\": {\n  \"query_time\": 1.86e-7,\n  \"powered_by\": \"crowdstrike-api-gateway\",\n  \"trace_id\": \"b41aa19c-71fa-4194-9e08-7d27fd74a654\"\n },\n \"errors\": [\n  {\n   \"code\": 401,\n   \"message\": \"access denied, authorization failed\"\n  }\n ]\n}", "content_encoding": "", "content_length": "231", "content_type": "application/json", "cookies": [], "date": "Thu, 03 Aug 2023 11:14:06 GMT", "elapsed": 0, "headers": ["Connection", "X-Content-Type-Options", "X-Cs-Traceid", "X-Ratelimit-Limit", "X-Ratelimit-Remaining", "Strict-Transport-Security", "Content-Length", "Content-Type", "Date", "Server"], "is_from_cache": false, "is_mutually_authenticated": false, "json": {"errors": [{"code": 401, "message": "access denied, authorization failed"}], "meta": {"powered_by": "crowdstrike-api-gateway", "query_time": 1.86e-07, "trace_id": "b41aa19c-71fa-4194-9e08-7d27fd74a654"}}, "last_modified": "2023-08-03T13:14:06.8912582+02:00", "method": "POST", "msg": "Status code of request '401' is not in list of valid status codes 201 308 : Unauthorized'.", "protocol_version": {"Build": -1, "Major": 1, "MajorRevision": -1, "Minor": 1, "MinorRevision": -1, "Revision": -1}, "response_uri": "https://api.crowdstrike.com/oauth2/token", "server": "nginx", "status_code": 401, "status_description": "Unauthorized", "strict_transport_security": "max-age=31536000; includeSubDomains", "supports_headers": true, "url": "https://api.crowdstrike.com/oauth2/token", "x_content_type_options": "nosniff", "x_cs_traceid": "b41aa19c-71fa-4194-9e08-7d27fd74a654", "x_ratelimit_limit": "300", "x_ratelimit_remaining": "299"}_`

is there a way I can test those id ?
PS. those ID are not the real ones.
