### ISSUE TITLE
Install crowdstrike on windows - Ansible not finishing

### ISSUE THREAD

**Issue by txsastre** [CrowdStrike/ansible_collection_falcon#378]
hi there 

I'm installing Crowdstrike url method.

Everything seems to work fine, but at the end the ansible node is not showing the statistics, indeed seems that it's still installing crowdstrike, but I checked on the machine, and it is also installed and running.

![imatge](https://github.com/CrowdStrike/ansible_collection_falcon/assets/10468371/59cc4912-c221-4605-bac9-28133ea009e3)

Also, if I run it again and error occurs, as it seems unable to delete a file.

`*
failed: [10.101.137.20] (item={'path': 'C:\\Windows\\Temp\\ansible.1zjnegtf.mmafalcon', 'extension': None, 'filename': 'ansible.1zjnegtf.mmafalcon', 'creationtime': 1691501278.5003443, 'checksum': None, 'size': None, 'isreadonly': False, 'attributes': 'Directory', 'lastaccesstime': 1691501290.3173146, 'isreg': False, 'isjunction': False, 'islnk': False, 'isarchive': False, 'lastwritetime': 1691501290.3173146, 'nlink': 1, 'isshared': False, 'ishidden': False, 'exists': True, 'isdir': True, 'lnk_target': None, 'sharename': None, 'hlnk_targets': [], 'lnk_source': None, 'owner': 'BUILTIN\\Administrators'}) => {"ansible_loop_var": "item", "changed": false, "item": {"attributes": "Directory", "checksum": null, "creationtime": 1691501278.5003443, "exists": true, "extension": null, "filename": "ansible.1zjnegtf.mmafalcon", "hlnk_targets": [], "isarchive": false, "isdir": true, "ishidden": false, "isjunction": false, "islnk": false, "isreadonly": false, "isreg": false, "isshared": false, "lastaccesstime": 1691501290.3173146, "lastwritetime": 1691501290.3173146, "lnk_source": null, "lnk_target": null, "nlink": 1, "owner": "BUILTIN\\Administrators", "path": "C:\\Windows\\Temp\\ansible.1zjnegtf.mmafalcon", "sharename": null, "size": null}, "msg": "Failed to delete C:\\Windows\\Temp\\ansible.1zjnegtf.mmafalcon\\WindowsSensor.LionLanner.exe: Access to the path 'C:\\Windows\\Temp\\ansible.1zjnegtf.mmafalcon\\WindowsSensor.LionLanner.exe' is denied."}
`

**Comment by carlosmmatos** [comment]
Possible issues here might be surrounding installation/provisioning tokens. Please make sure you check what is required on your end for installing a sensor and provide the appropriate installation args.

**Comment by txsastre** [comment]
also I left the "unfinished playbook" running, and now I see

`"FAILED - RETRYING: [192.168.70.162]: CrowdStrike Falcon | Install Falcon Sensor .exe Package (Windows) (10 retries left)."`

**Comment by txsastre** [comment]
Tried again with verbose and I can see this

```
FAILED - RETRYING: [192.168.70.162]: CrowdStrike Falcon | Install Falcon Sensor .exe Package (Windows) (2 retries left).Result was: {
    "attempts": 1,
    "changed": false,
    "invocation": {
        "module_args": {
            "arguments": "/install /quiet CID=8A3EFADB098A4EABAA3F441B1B137EFB-E8 /norestart",
            "chdir": null,
            "client_cert": null,
            "client_cert_password": null,
            "creates_path": null,
            "creates_service": "csfalconservice",
            "creates_version": null,
            "expected_return_code": [
                0,
                3010
            ],
            "follow_redirects": "safe",
            "force_basic_auth": false,
            "headers": null,
            "http_agent": "ansible-httpget",
            "log_path": null,
            "maximum_redirection": 50,
            "path": "C:\\Windows\\Temp\\ansible.yysrtj0e.udufalcon\\WindowsSensor.LionLanner.exe",
            "product_id": null,
            "provider": "auto",
            "proxy_password": null,
            "proxy_url": null,
            "proxy_use_default_credential": false,
            "proxy_username": null,
            "state": "present",
            "url_method": null,
            "url_password": null,
            "url_timeout": 30,
            "url_username": null,
            "use_default_credential": false,
            "use_proxy": true,
            "validate_certs": true,
            "wait_for_children": false
        }
    },
    "msg": "unexpected rc from 'C:\\Windows\\Temp\\ansible.yysrtj0e.udufalcon\\WindowsSensor.LionLanner.exe /install /quiet CID=8A3EFADB098A4EABAA3F441B1B137EFB-E8 /norestart': see rc, stdout, and stderr for more details",
    "rc": 1244,
    "reboot_required": false,
    "retries": 3,
    "stderr": "",
    "stderr_lines": [],
    "stdout": "",
    "stdout_lines": []

```

**Comment by carlosmmatos** [comment]
Please refer to the role documentation. You have to specify additional install/uninstall args. Look at `falcon_windows_install_args`

**Comment by txsastre** [comment]
also tried with standard ansible, with no crowdstrike collection

```
---
- name: Tasks to download file
  hosts: all
  gather_facts: no
  
  tasks:
  - name: Download CrowdStrike
    ansible.windows.win_get_url:
     url: http://192.168.70.134/software/WindowsSensor.LionLanner.exe
     dest: c:\temp
     force: false
     
  - name: Install CrowdStrike
    win_shell: 'c:\temp\WindowsSensor.LionLanner.exe /install /quiet /norestart CID=12342134123412341234123412341234-12'
```

Fun fact is meanwhile is "stuck" I can see that the sensor is running, and the other fact is after 20 minutes "stuck" it has finally stopped, but the sensor has gone too.

**Comment by txsastre** [comment]
ok, tried with token, same luck, it gets stuck
```

---
- name: Tasks to download file
  hosts: all
  gather_facts: no
  
  tasks:
  - name: Download CrowdStrike
    ansible.windows.win_get_url:
     url: http://192.168.70.134/software/WindowsSensor.LionLanner.exe
     dest: c:\temp
     force: false
     
  - name: Install CrowdStrike
    win_shell: 'c:\temp\WindowsSensor.LionLanner.exe /install /quiet /norestart CID=12342134123412341234123412341234-12 MAINTENANCE_TOKEN=123456789'
```

**Comment by carlosmmatos** [comment]
I don't think that's the correct argument. Try ProvToken=<provisioning token>

Also, check the installation logs on the system if it still isn't working. Most of this stuff should be in the sensor installation documentation for more clarity.

**Comment by txsastre** [comment]
Good morning!

That was the problem, I replaced MAINTENANCE_TOKEN with **ProvToken** and it worked fine! Thank you very much for your help !

Tried in my lab with 3 servers at once and the agent was installed in 2 minutes in total  :D

Just a question, what's the equivalent of **ProvToken** in the crowdstrike vars ? Because I used "falcon_client_secret" but it didn't work, it gets stuck.

Also, what's the difference, using the crowdstrike collection instead of the ansible.windows.win_package?

Thank you very much again!

**Comment by carlosmmatos** [comment]
@txsastre Perhaps you missed my last post about consulting the role's [README](https://github.com/CrowdStrike/ansible_collection_falcon/blob/main/roles/falcon_install/README.md?plain=1#L41C11-L41C11). This should be the variable you are looking for, along with all the other variables the role accepts. 

Try the following in your playbook:
```yaml
---
- hosts: all
  roles:
  - role: crowdstrike.falcon.falcon_install
    vars:
      falcon_install_method: url
      falcon_download_url: 'http://192.168.70.134/software/WindowsSensor.LionLanner.exe'
      falcon_client_id: '123412341234123412341234123412341-12'
      falcon_cid: '123412341234123412341234123412341-12'
      falcon_windows_install_args: '/norestart ProvToken=D0B1BD55'
```
