### ISSUE TITLE
Removing AID failing in crowdstrike.falcon.falcon_configure

### ISSUE THREAD

**Issue by tremahts** [CrowdStrike/ansible_collection_falcon#388]
We're running a packer build into AWS generating RHEL images and after installing the agent, the task where the AID is removed is failing due to what looks to be a missing agent. Curious what I'm missing here. Thanks.

Ansible version: 2.15.2
Same behavior on both RHEL 8 and 9.

Task:
```
  roles:
    - role: crowdstrike.falcon.falcon_install
    - role: crowdstrike.falcon.falcon_configure
      vars:
        falcon_option_set: false
        falcon_remove_aid: true
```
Output:
```
packer-rhel.amazon-ebs.rhel-8: TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Install Falcon Sensor Package (Linux)] ***
    packer-rhel.amazon-ebs.rhel-8: changed: [default]
```

```
packer-rhel.amazon-ebs.rhel-8: TASK [crowdstrike.falcon.falcon_configure : CrowdStrike Falcon | Remove Falcon Agent ID (AID) If Building A Primary Image] ***
    packer-rhel.amazon-ebs.rhel-8: fatal: [default]: FAILED! => {"changed": false, "msg": "Failed to find required executable \"falconctl\" in paths: `/opt/CrowdStrike:/home/ec2-user/.local/bin:/home/ec2-user/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin"}
```

**Comment by carlosmmatos** [comment]
@tremahts The error you are seeing is indicating that the `/opt/CrowdStrike/falconctl` executable is missing. Usually this indicates that the falcon-sensor hasn't been installed. Hard to tell from your output what is happening, but I would double check that the falcon_install role is indeed installing the sensor.

**Comment by carlosmmatos** [comment]
@tremahts One thing I just thought of as well that you may be running into is not using the correct user/permissions needed. 

For example, try running your playbook like this:

```yaml
  roles:
    - role: crowdstrike.falcon.falcon_install
    - role: crowdstrike.falcon.falcon_configure
      become: yes
      vars:
        falcon_option_set: false
        falcon_remove_aid: true
```

I see that the remove AID block is not forcibly setting become: yes like other tasks, so I will create an PR to fix this. But the above should work for you in the meantime.
