### ISSUE TITLE
crowdstrike.falcon.falcon_install not using proxy

### ISSUE THREAD

**Issue by bmarshallop** [CrowdStrike/ansible_collection_falcon#442]
This was previously working but we discovered crowdstrike.falcon.falcon_install is now failing with "Sorry, try again" on the Authenticate to CrowdStrike API task. We have set the variables accordingly
    falcon_apd: false
    falcon_aph: "http://192.168.212.129"
    falcon_app: 3130

During the install if I run tcpdump on the target host and tail logs on the proxy and I never see any calls got out to the proxy. But if I go directly to the target host I can successfully curl to api.us-2.crowdstrike.com through the proxy.

Using crowdstrike.falcon 4.2.1

**Comment by carlosmmatos** [comment]
@bmarshallop - thanks for opening this up! 

The task `CrowdStrike Falcon | Authenticate to CrowdStrike API` happens at the localhost level. As of V4, since we are now using our own modules to communicate with the API via FalconPy, most of our API calls in our roles will be delegated to the localhost (which is where you would have installed the pre-reqs).

If you want to use a proxy with Ansible, you need to set the proper proxy env variable for it. This isn't anything special to CrowdStrike, this would be specific to Ansible. Check out the following [Ansible docs](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_environment.html). 

As for the `falcon_ap*` variables, these are used to set the sensor up once it's been installed, so they wouldn't have an impact on your authentication task.

---

Some things to check:

- Can your localhost system directly authenticate with Falcon? This is what makes the API calls and will do all the downloading of the sensor before pushing it to the remote host.
- Do the tcpdump on the localhost - after making changes to support proxies with Ansible (refer to docs).

**Comment by bmarshallop** [comment]
@carlosmmatos  Thanks for the reply. 

I am using proxy configurations. The host I am running the play book from (controller) has proxy configurations as does the remote host. Both are configure via /etc/environment and I also have proxy configurations defined in the playbook per the Ansible doc you reference. 

When the playbook runs it never attempts to contact the proxy. For eaxmple in the playbook below I define the proxy configuration for the falcon sensor as well as the environment. The controller uses different proxy URL's than the target host which are from awsvars and edcvars respectively. 

`---
- hosts: "{{ variable_host | default('developers, vault, devops') }}"
  remote_user: oplus
  become: yes
  vars_files:
  - vars.yml
  - enc.yml
  environment:
    http_proxy: "{{awsvars.http_proxy}}"
    https_proxy: "{{awsvars.https_proxy}}"
  vars:
    ansible_become_pass: "{{ encvars.opluspwd }}"
    falcon_cloud: us-2
    falcon_client_id: "{{ encvars.falcon_client_id}}"
    falcon_client_secret: "{{ encvars.falcon_client_secret}}"
    falcon_cid: "{{ encvars.falcon_cid }}"
    falcon_apd: false
    falcon_aph: "{{edcvars.proxy_url}}"
    falcon_app: 3130
    falcon_api_enable_no_log: false
  roles:
    - crowdstrike
`
Am I doing something wrong here or is this indeed not working as intended?

**Comment by carlosmmatos** [comment]
Let's start with the error output and see where it takes us.. 

Can you run it with `-vvv` and paste the output of the task that fails (make sure to scrub any sensitive data).

**Comment by bmarshallop** [comment]
@carlosmmatos Thanks, see below for the task output. It is using the correct proxy for the controller that I have obfuscated as 172.25.X.X 

```
TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Authenticate to CrowdStrike API] *******************************************************************************************************************
task path: /home/bmarshall/.ansible/collections/ansible_collections/crowdstrike/falcon/roles/falcon_install/tasks/auth.yml:2
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: bmarshall
<localhost> EXEC /bin/sh -c 'echo ~bmarshall && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/bmarshall/.ansible/tmp `"&& mkdir "` echo /home/bmarshall/.ansible/tmp/ansible-tmp-1705337029.4979038-15747-256673692420187 `" && echo ansible-tmp-1705337029.4979038-15747-256673692420187="` echo /home/bmarshall/.ansible/tmp/ansible-tmp-1705337029.4979038-15747-256673692420187 `" ) && sleep 0'
Using module file /home/bmarshall/.ansible/collections/ansible_collections/crowdstrike/falcon/plugins/modules/auth.py
<localhost> PUT /home/bmarshall/.ansible/tmp/ansible-local-15667tu_puk_6/tmpij9_c37z TO /home/bmarshall/.ansible/tmp/ansible-tmp-1705337.....692420187/AnsiballZ_auth.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/bmarshall/.ansible/tmp/ansible-tmp-1705337029.4979038-15747-256673692420187/ /home/bmarshall/.ansible/tmp/ansible-tmp-1705337029.4979038-15747-256673692420187/AnsiballZ_auth.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S -p "[sudo via ansible, key=uzfpo........ysq] password:" -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-uzfpogb.....yqgdysq ; http_proxy=http://172.25.X.X:3129/ https_proxy=http://172.25.X.X:3130/ /usr/bin/python3 /home/bmarshall/.ansible/tmp/ansible-tmp-1705337029.4979038-15747-256673692420187/AnsiballZ_auth.py'"'"' && sleep 0'
Sorry, try again.

```

**Comment by carlosmmatos** [comment]
Yeah this doesn't look right at all.. this looks like the output of trying to become the root user.. almost like the become is failing to authenticate since this is the last step. Otherwise we should see one more EXEC before the module is executed. 

Can you verify that the playbook can properly `become` with the provided credentials?

Maybe try something like this:

```yaml
---
- hosts: "{{ variable_host | default('developers, vault, devops') }}"
  remote_user: oplus
  become: yes
  vars_files:
  - vars.yml
  - enc.yml
  environment:
    http_proxy: "{{awsvars.http_proxy}}"
    https_proxy: "{{awsvars.https_proxy}}"
  vars:
    ansible_become_pass: "{{ encvars.opluspwd }}"
    falcon_cloud: us-2
    falcon_client_id: "{{ encvars.falcon_client_id}}"
    falcon_client_secret: "{{ encvars.falcon_client_secret}}"
    falcon_cid: "{{ encvars.falcon_cid }}"
    falcon_apd: false
    falcon_aph: "{{edcvars.proxy_url}}"
    falcon_app: 3130
    falcon_api_enable_no_log: false
  tasks:
    - name: Check if /root directory exists
      ansible.builtin.stat:
        path: /root
      register: root_dir
```
