### ISSUE TITLE
Access denied in ansible inventory

### ISSUE THREAD

**Issue by Gianlu** [CrowdStrike/ansible_collection_falcon#458]
Hi,
I'm trying to use the ansible inventory but I reveive a 
```
Unable to query hosts: [{'code': 403, 'message': 'access denied, authorization failed'}]
```
I'm pretty sure that client_id and client_secret are right because via curl I'm authenticated.
My token is associated to a policy with read grant on all entities.

May you help me?

Thanks

**Comment by carlosmmatos** [comment]
Hello @Gianlu - apologies as I noticed that I did not add the API Scope to the dynamic inventory in order to use it. Can you try adding the following API Scope to your credentials?

- assets [**READ**]

**Comment by Gianlu** [comment]
Hello,
Sorry, where I have to define the scope? In crowdstryke console, I have full read for every single scope and I can't see the asset scope. 
Moreover, with same credentials the falconpy samples work (es get_dups.py). 

Thanks

**Comment by carlosmmatos** [comment]
Which falconpy sample are you referring to? Also, would you mind sharing your dynamic inventory file configuration?

**Comment by Gianlu** [comment]
Hello,
my inventory file is:
```YAML
# filename: 20_my_inventory.falcon_discover.yml
plugin: crowdstrike.falcon.falcon_discover

client_id: '*****************'
client_secret: '************************'
cloud: eu-1
```
The duplicate finder is [duplicate_sensors.py](https://github.com/CrowdStrike/falconpy/blob/main/samples/hosts/duplicate_sensors.py)

Thanks
