### ISSUE TITLE
Ubuntu 24.04 support

### ISSUE THREAD

**Issue by ktinthecloud** [CrowdStrike/ansible_collection_falcon#530]
Does this collection support Ubuntu 24.04 yet?

**Comment by carlosmmatos** [comment]
@ktinthecloud - the short answer is no, we don't officially support 24.04 yet - I believe it's slated for 7.17+ but until CRWD makes it official there is nothing we can do about that part.

I will say that there is an unofficial way you may be able to do this. Basically you will install the latest sensor from ubuntu 22.04 and it should run in user-mode (ebpf). 
> [!WARNING]
> This is not supported from CRWD

If you are interested in testing this out from our collection, you can try the following for `falcon_install`:

```yaml
---
- hosts: all
  roles:
  - role: crowdstrike.falcon.falcon_install
    vars:
      falcon_client_id: <FALCON_CLIENT_ID>
      falcon_client_secret: <FALCON_CLIENT_SECRET>
      falcon_os_version: "*22*"
```

You are basically overriding the default: `falcon_os_version: "*{{ ansible_facts['distribution_major_version'] }}*"`
