### ISSUE TITLE
Machine spawed from master image does not have AID

### ISSUE THREAD

**Issue by ongyo-sensei** [CrowdStrike/ansible_collection_falcon#534]
Hello,

I created master image for my VM setup, and when I spawn new machine I dont have AID set.

I deployed with agent to master with `falcon_remove_aid: true` as suggested here - https://github.com/CrowdStrike/ansible_collection_falcon/blob/0e86d792b080e16eb1479bac0f1e9195b1e6b0bc/roles/falcon_configure/defaults/main.yml#L47

Unfortunately every new image does not have AID.

Logs are looking ok - access to internet is ok and agent connects to CS API endpoint.

What should I do? How to force new machines to get AID.

**Comment by carlosmmatos** [comment]
@ongyo-sensei Would you mind showing me an example of your playbook you are using for this?

**Comment by ongyo-sensei** [comment]
Sure following is the  yaml:

```
- hosts: cicdhosts
  vars:
    falcon_client_id: CLIENT_ID 
    falcon_client_secret: CLIENT_SECRET
    falcon_provisioning_token: PROVISION_TOKEN 
    ## needed to remove AID for golden image to generate new AID per new instance
    falcon_remove_aid: true
    falcon_option_set: yes
    falcon_api_enable_no_log: no
  roles:
#  - role: falcon_uninstall
  - role: falcon_install
    vars:
      falcon_sensor_version_decrement: 1
  - role: falcon_configure
    vars:
      # falcon_cid is autodetected using falcon_client_id|secret vars
      falcon_tags: 'cicdhosts'

```

I am executing following command:
`ansible-playbook -i inventory.ini cs-agent-golden-image.yaml -e 'ansible_python_interpreter=python3.11'
`
Do you need anything else?

We are preparing image for CICD piplines and then we spawn new machines from that image...

**Comment by alvicsam** [comment]
We use packer. The packer build section looks like this:

```hcl

...

build {
  source "source.googlecompute.this" {
    name       = "main"
    image_name = local.image_name
  }

  provisioner "shell" {
    inline = [
      "echo 'Acquire::AllowReleaseInfoChange \"true\";' | sudo tee /etc/apt/apt.conf.d/99-allow-release-info-change.conf",
      "sudo DEBIAN_FRONTEND=noninteractive apt-get update",
      "sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y",
      "sudo DEBIAN_FRONTEND=noninteractive apt-get install -y mdadm"
    ]
  }

  provisioner "ansible" {
    use_proxy = false

    galaxy_file      = "./requirements.yaml"
    collections_path = "./collections/${source.name}" # separate collections per build to avoid races
    ansible_env_vars = ["ANSIBLE_COLLECTIONS_PATH=./collections/${source.name}"]

    playbook_file = "./playbook.yaml"
    extra_arguments = [
      "-e", "ansible_python_interpreter=/usr/bin/python3",
      "-t", "crowdstrike"
    ]
  }

...

}

```

And the playbook.yaml looks like:

```yaml
- name: crowdstrike
  hosts: default
  vars:
    falcon_client_id: 
    falcon_client_secret: 
    falcon_provisioning_token:
    ## needed to remove AID for golden image to generate new AID per new instance
    falcon_remove_aid: true
    falcon_option_set: yes
    falcon_api_enable_no_log: no
  roles:
    - role: falcon_install
      vars:
        falcon_sensor_version_decrement: 1
    - role: falcon_configure
      vars:
        # falcon_cid is autodetected using falcon_client_id|secret vars
        falcon_tags: "cicdhosts"
  tags:
    - crowdstrike
```

requirements.yaml:

```
collections:
...
  - crowdstrike.falcon

```

**Comment by carlosmmatos** [comment]
I'll take a look today to see if I can replicate any issues.. but just to ensure I'm understanding the situation correctly, based on the playbook you provided it should:
- Install the sensor
- Configure the sensor
  - adds cid + tags
  - restarts the service - this generates the first aid
  - removes the aid

At that point your system should shut down - and then you are saying when you spin a new system from that image, it's not generating an AID correct?

**Comment by carlosmmatos** [comment]
@alvicsam | @ongyo-sensei  sorry for the late reply.. So I just tested this using your playbook as the example on a standalone Ubuntu 22 system, rebooted, and got a new AID.

Without assuming this is related to Packer.. what OS/distro are you using that perhaps I can try to reproduce it on there?

**Comment by alvicsam** [comment]
@carlosmmatos thank you for the answer! We are using GCP image with debian: `debian-11-bullseye-v20240213`

**Comment by ongyo-sensei** [comment]
@carlosmmatos Hey did you manage to replicate issue or still all OK on your side?

**Comment by carlosmmatos** [comment]
Have not, sorry. Let me spin one up with that OS and see what I get.

**Comment by carlosmmatos** [comment]
@ongyo-sensei | @alvicsam can confirm I'm seeing the same issue as you now. However, I don't think this is an Ansible issue or issue with this collection. I've confirmed the same thing happens when installing it via shell script. 

For this, you will need to open a support case with [Crowdstrike Support ](https://supportportal.crowdstrike.com/). 

If you don't mind, keep us updated on the what they find.

**Comment by carlosmmatos** [comment]
@ongyo-sensei | @alvicsam - quick update from more testing. 

This seems to be working fine outside of GCP. For example, I used Vagrant image: https://app.vagrantup.com/debian/boxes/bullseye64 and ran the same tests and upon reboot, I'm seeing a new AID issued. Just something to think about as you guys work through support.

**Comment by ongyo-sensei** [comment]
OK thank you for your help. We will create support ticket - GCP is obviously not supported by CS...

**Comment by carlosmmatos** [comment]
I would work with both - GCP support and CS support.  If there is something on the GCP end in their base image that affects CS sensor then it makes sense both parties are aware of what's going on so more folks may be notified about potential issues. But either way, whatever path you choose, I'm definitely interested in learning about the outcome.

**Comment by nhinds** [comment]
I've found the same thing after upgrading from 4.1.3 to 4.5.1, running in EC2. Our crowdstrike tenant is configured to require installation/provisioning tokens, and it seems like the current Ansible role does not support this.

Applying the `falcon_configure` role with `falcon_provisioning_token: <token>` and `falcon_remove_aid: yes`:
* Sets the CID and provisioning token
* Activates the agent, which generates an AID and consumes/removes the provisioning token from the falcon agent
* Removes the AID

At this point the agent is installed but the provisioning token is not set (e.g. `falconctl -g --provisioning-token` returns `provisioning-token is not set.`), and if I create an AMI then new machines launched from the image cannot activate falcon. This can be verified without creating an image too: restarting the `falcon-sensor` service or rebooting the machine should regenerate the agent ID at this point, but it does not.

In version 4.1.3 the way I prepared a base image was to set `falcon_provisioning_token: <token>` and `falcon_service_state: stopped`. This ensured that no agent ID was ever generated, and the provisioning token was not consumed. The changes from #486 added a task "CrowdStrike Falcon | Wait for Falcon Sensor to Generate AID" which now fails if I pass `falcon_service_state: stopped`, because the AID is (intentionally) never generated if the service is stopped, so this approach no longer works.

A workaround that works for me is to re-set the provisioning token after applying the `falcon_configure` role, e.g.
```
- hosts: all
  vars:
    falcon_client_id: CLIENT_ID 
    falcon_client_secret: CLIENT_SECRET
    falcon_provisioning_token: PROVISION_TOKEN 
    ## needed to remove AID for golden image to generate new AID per new instance
    falcon_remove_aid: true
  roles:
  - role: falcon_install
  - role: falcon_configure
  tasks:
  - name: Reapply falcon provisioning token to work around CrowdStrike/ansible_collection_falcon#534
    crowdstrike.falcon.falconctl:
      cid: "{{ falcon_cid }}"
      provisioning_token: "{{ falcon_provisioning_token }}"
      state: present
```

But ideally, if `falcon_remove_aid` is true it would be nice if the role could avoid generating an aid in the first place, or (re-)set the provisioning token after removing any `aid` that was already present.
